version: '3'

services:
  app:
    build: .
    ports:
      - "3001:8000"
    volumes:
      - ./processed_stats:/app/processed_stats
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=8000