version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./processed_stats:/app/processed_stats
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=8000
    # Add healthcheck to verify container is working properly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s