[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[[services]]
internal_port = 8000
protocol = "http"

  [[services.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

  [[services.ports]]
  port = 443
  handlers = ["http", "tls"]